### ISSUE TITLE
out of bounds for axis 2

### ISSUE THREAD

**Issue by xunkaixin** [BenWhetton/keras-surgeon#11]
Hi,
  thanks, good work

 when pruning, some problems:

    return surgeon.operate()
  File "C:\Users\qkj\Anaconda3\lib\site-packages\kerassurgeon\surgeon.py", line 158, in operate
    self._mod_func_map[node](node, outputs, output_masks, **kwargs)
  File "C:\Users\qkj\Anaconda3\lib\site-packages\kerassurgeon\surgeon.py", line 309, in _delete_channels
    new_delete_mask = self._make_delete_mask(old_layer, channels)
  File "C:\Users\qkj\Anaconda3\lib\site-packages\kerassurgeon\surgeon.py", line 676, in _make_delete_mask
    new_delete_mask[..., channel_indices] = False
IndexError: index 12 is out of bounds for axis 2 with size 6

**Comment by BenWhetton** [comment]
Hi there,
Please post a code sample which enables me to reproduce the problem if you would still like help with this.

**Comment by souravehossain** [comment]
Hi Ben, I'm also getting the same error while I'm trying to prune the last conv2d layer of dense121 from keras.application.densenet

following is the code I'm trying to run

def prune_me(model, layer_name, val_images):
    layer = model.get_layer(name=layer_name)
    apoz = identify.get_apoz(model, layer, val_images)
    high_apoz_channels = identify.high_apoz(apoz)
    model = delete_channels(model, layer, high_apoz_channels)

    model.compile(Adam(lr=.0001), loss='categorical_crossentropy', metrics=['accuracy'])

    loss = model.evaluate_generator(test_batches, steps=20, verbose=1)
    print('model loss after pruning: ', loss, '\n')
    print('retraining started')
    results = model.fit_generator(train_batches, steps_per_epoch=163, validation_data = test_batches, 
                    validation_steps=20, epochs=5, verbose=1, callbacks=[lr_reduce,checkpoint])
    print('retraining done')
    loss = model.evaluate_generator(test_batches, steps=20, verbose=1)
    print('model loss after retraining: ', loss, '\n')

in my case, val_images is an ImageDataGenerator

error message:
IndexError                                Traceback (most recent call last)
<ipython-input-35-a6a5f65e830c> in <module>()
----> 1 model = delete_channels(model, layer, high_apoz_channels)

/usr/local/lib/python3.6/site-packages/kerassurgeon/operations.py in delete_channels(model, layer, channels, node_indices, copy)
    103     surgeon = Surgeon(model, copy)
    104     surgeon.add_job('delete_channels', layer, node_indices=node_indices, channels=channels)
--> 105     return surgeon.operate()

/usr/local/lib/python3.6/site-packages/kerassurgeon/surgeon.py in operate(self)
    156             # Perform surgery at this node
    157             kwargs = self._kwargs_map[node]
--> 158             self._mod_func_map[node](node, outputs, output_masks, **kwargs)
    159 
    160         # Finish rebuilding model

/usr/local/lib/python3.6/site-packages/kerassurgeon/surgeon.py in _delete_channels(self, node, inputs, input_masks, channels, layer_name)
    307         old_layer_output = utils.single_element(node.output_tensors)
    308         # Create a mask to propagate the deleted channels to downstream layers
--> 309         new_delete_mask = self._make_delete_mask(old_layer, channels)
    310 
    311         if len(set(channels)) == getattr(old_layer, utils.get_channels_attr(old_layer)):

/usr/local/lib/python3.6/site-packages/kerassurgeon/surgeon.py in _make_delete_mask(self, layer, channel_indices)
    670             new_delete_mask[channel_indices, ...] = False
    671         elif data_format == 'channels_last':
--> 672             new_delete_mask[..., channel_indices] = False
    673         else:
    674             ValueError('Invalid data_format property value')

IndexError: index 32 is out of bounds for axis 2 with size 32

**Comment by BenWhetton** [comment]
Hi there. Could you please post an example script that I can execute so that I can debug it?
Thanks, Ben

**Comment by souravehossain** [comment]
https://github.com/souravehossain/pruning-densnet121/blob/master/prune.ipynb

this link has the script I'm trying to execute. Please let me know if I missed anything.

Thanks.

**Comment by BenWhetton** [comment]
Ok. I really need a self-contained script which I can put in a .py file which reproduces your issue without needing any external data or I can't run it to debug. Or at the very worst, a script which requires a small amount of external data and good instructions for where to get it from and where to put it for the script to work.

The best I can do with the notebook you send is this:
```
from keras.applications.densenet import DenseNet121
from keras.layers import Dense
from keras.models import Model
from kerassurgeon.operations import delete_channels
import kerassurgeon

print(kerassurgeon.__version__)

base_model = DenseNet121(weights=None)

x = base_model.layers[-2].output
predictions = Dense(2, activation='softmax')(x)
model = Model(inputs=base_model.input, outputs=predictions)

model.summary()

layer_name = 'conv5_block16_2_conv'
layer = model.get_layer(name=layer_name)
model = delete_channels(model, layer, [0])
```

I don't get any problems though. Check if you get any problems running the above script (just dump it in a .py file and run it). If you get issues, it might be something to do with a difference between your python and libraries versions and mine. Otherwise, please try to create a minimal script which reproduces your problem.

**Comment by souravehossain** [comment]
Hi Ben, Really sorry for the delay and I really appreciate you helping out. 
I've attached a zip file that contains a .py file that has all the codes and necessary instructions on how to get the dataset (1GB)
[prune.zip](https://github.com/BenWhetton/keras-surgeon/files/2484082/prune.zip)

Thanks.

**Comment by BenWhetton** [comment]
Hi. Thanks for providing the file. I'll have a look at it as soon as I get some more time to work on this.

For future info, if you're just sharing text, a link to a gist on https://gist.github.com/ or something similar would be better :)

**Comment by BenWhetton** [comment]
I finally got time to have a good look into this. I've worked out what the problem is but unfortunately it isn't an easy fix.

If the layer to be pruned doesn't have a built in activation, the `get_apoz` algorithm calls `utils.find_activation_layer` to find the first downstream activation layer, it counts the number of zeros at the activation layer's output. Unfortunately if output of the layer to be pruned is combined with the output of another layer before the activation layer (with a `Concatenate` layer, for example), currently it cannot determine which channels from the activation layer correspond to the pruned layer output channels.

Here are the last few layers in the network from your example:
```
__________________________________________________________________________________________________
conv5_block16_2_conv (Conv2D)   (None, 7, 7, 32)     36864       conv5_block16_1_relu[0][0]       
__________________________________________________________________________________________________
conv5_block16_concat (Concatena (None, 7, 7, 1024)   0           conv5_block15_concat[0][0]       
                                                                 conv5_block16_2_conv[0][0]       
__________________________________________________________________________________________________
bn (BatchNormalization)         (None, 7, 7, 1024)   4096        conv5_block16_concat[0][0]       
__________________________________________________________________________________________________
relu (Activation)               (None, 7, 7, 1024)   0           bn[0][0]                         
__________________________________________________________________________________________________
avg_pool (GlobalAveragePooling2 (None, 1024)         0           relu[0][0]                       
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 2)            2050        avg_pool[0][0]                   
```
You are trying to prune `conv5_block16_2_conv` which is concatenated with many other layers before the `relu` activation layer.

I don't expect I'm going to have time to add support for that kind of network any time soon, sorry. I'm going to add a check for layers with multiple inputs between the pruned layer and the activation layer and raise an error if any are found which will at least make the failure an expected behaviour.

**Comment by cjt222** [comment]
Have this problem solved? Have you try to prune mobilenetv2? how to solve Multiple input in short?
