### ISSUE TITLE
replacing Add layer with Concatenate layer

### ISSUE THREAD

**Issue by melhoushi-invn** [BenWhetton/keras-surgeon#13]
Hi
I am trying to replace an Add layer with Concatenate layer using this lines:

```
for layer in model.layers:
    if layer.name == "add_12":
        add_layer = layer

new_layer = Concatenate()()

new_model = replace_layer(model, add_layer, new_layer, copy=False)
```
but I get this error message:

> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 426, in assert_input_compatibility
>     K.is_keras_tensor(x)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 458, in is_keras_tensor
>     raise ValueError('Unexpectedly found an instance of type `' + str(type(x)) + '`. '
> ValueError: Unexpectedly found an instance of type `<class 'tuple'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:
 
> Traceback (most recent call last):
>   File "main.py", line 67, in <module>
>     new_model = replace_layer(model, add_layer, new_layer, copy=False)
>   File "keras-surgeon/src/kerassurgeon/operations.py", line 71, in replace_layer
>     return surgeon.operate()
>   File "keras-surgeon/src/kerassurgeon/surgeon.py", line 159, in operate
>     self._mod_func_map[node](node, outputs, output_masks, **kwargs)
>   File "keras-surgeon/src/kerassurgeon/surgeon.py", line 297, in _replace_layer
>     new_output = new_layer(utils.single_element(inputs))
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 559, in __call__
>     self.assert_input_compatibility(inputs)
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 432, in assert_input_compatibility
>     str(inputs) + '. All inputs to the layer '
> ValueError: Layer concatenate_1 was called with an input that isn't a symbolic tensor. Received type: <class 'tuple'>. Full input: [(<tf.Tensor 'activation_22_1/Tanh:0' shape=(?, ?, ?, 1) dtype=float32>, <tf.Tensor 'input_2:0' shape=(?, 64, 136, 1) dtype=float32>)]. All inputs to the layer should be tensors.
> 

I tried to replace this line:
`new_layer = Concatenate()()`
with this line:
`new_layer = Concatenate()(add_layer.input)`

but I then get this error message:

> Traceback (most recent call last):
>   File "main.py", line 67, in <module>
>     new_model = replace_layer(model, add_layer, new_layer, copy=False)
>   File "keras-surgeon/src/kerassurgeon/operations.py", line 71, in replace_layer
>     return surgeon.operate()
>   File "keras-surgeon/src/kerassurgeon/surgeon.py", line 159, in operate
>     self._mod_func_map[node](node, outputs, output_masks, **kwargs)
>   File "keras-surgeon/src/kerassurgeon/surgeon.py", line 297, in _replace_layer
>     new_output = new_layer(utils.single_element(inputs))
> TypeError: 'Tensor' object is not callable
>

**Comment by BenWhetton** [comment]
This tool can only replace layers which have the same shape inputs and outputs.
If the input to the Add layer is m tensors with shape n*p, the output shape of the Add layer would be n*p whereas the output shape of a Concatenate layer in the same place would be n*p*m.

Keras Surgeon's goal is to preserve weights when performing network surgery and this isn't possible for the subsequent layers in your case since their input shape would be different.

Does that make sense to you?

**Comment by BenWhetton** [comment]
Closing due to inactivity.
