### ISSUE TITLE
when I try to run lenet_mnist.py I got error below

### ISSUE THREAD

**Issue by gaojiaxi** [BenWhetton/keras-surgeon#15]
Traceback (most recent call last):

  File "<ipython-input-1-9d77235d6712>", line 1, in <module>
    runfile('C:/Users/gaojiaxi/Desktop/keras-surgeon-master/src/kerassurgeon/examples/lenet_mnist.py', wdir='C:/Users/gaojiaxi/Desktop/keras-surgeon-master/src/kerassurgeon/examples')

  File "C:\Users\gaojiaxi\Anaconda3\envs\Python35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\gaojiaxi\Anaconda3\envs\Python35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/gaojiaxi/Desktop/keras-surgeon-master/src/kerassurgeon/examples/lenet_mnist.py", line 97, in <module>
    main()

  File "C:/Users/gaojiaxi/Desktop/keras-surgeon-master/src/kerassurgeon/examples/lenet_mnist.py", line 67, in main
    apoz = identify.get_apoz(model, layer, val_images)

  File "C:\Users\gaojiaxi\Anaconda3\envs\Python35\lib\site-packages\kerassurgeon\identify.py", line 63, in get_apoz
    x_val, x_val.n // x_val.batch_size)

AttributeError: 'numpy.ndarray' object has no attribute 'n'

**Comment by pjd-ds** [comment]
Change:
>x_val, x_val.n// x_val.batch_size)
to 
>x_val, x_val.len // x_val.batch_size
