### ISSUE TITLE
Error when trying to run "python inception_flowers_prune.py"

### ISSUE THREAD

**Issue by pengpaiSH** [BenWhetton/keras-surgeon#2]
@BenWhetton Thank you for sharing this useful tool, which helps to reduce ConvNets model size
by pruning layers. When trying to run the example, I ran into the following error.

Using TensorFlow backend.
Traceback (most recent call last):
  File "inception_flowers_prune.py", line 19, in <module>
    from kerassurgeon.identify import get_apoz
  File "build/bdist.linux-x86_64/egg/kerassurgeon/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kerassurgeon-0.0.1-py2.7.egg/kerassurgeon/surgeon.py", line 53
    def add_job(self, job, layer, *,
                                   ^

**Comment by rovim** [comment]
I think that would only work for python 3 (I'm guessing you are using python 2.7?)

For me it worked when I deleted the * as an input parameter (as I'm using python 2.7):


` def add_job(self, job, layer, channels=None, new_layer=None, node_indices=None):
 ...`

**Comment by BenWhetton** [comment]
Hi there! Which version of python are you using? Python 2 is not supported so that might be the problem.
